import Head from "next/head";
import Login from "../components/Login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.svg" />
      </Head>
      <Login />
    </div>
  );
}
